version: "3.9"
services:
  template_db:
    build: ./db/
    image: template_db:1.0
    init: true
    user: "54321:54321"
    volumes:
      - ./db/pgdata:/var/pgdata
      - ./db/ddl:/var/ddl
      - ./nfs:/var/nfs
    ports:
      - "55432:15432"
    networks:
      template_net:
        ipv4_address: 172.18.0.30
    environment:
      - PGDATA=/var/pgdata/data
      - DB_NAME=TEMPLATE_DB
      - DB_PORT=15432
      - DB_PASS=postgres1234
    shm_size: 1.2gb

  template_node:
    build: ./node/
    image: template_node:1.0
    user: "node"
    working_dir: /var/node
    init: true
    ports:
      - "53000:3000"
    networks:
      template_net:
        ipv4_address: 172.18.0.10
    volumes:
      - ../src:/var/node
      - ./nfs:/var/nfs
    env_file:
      - ./node/.env
    command: "bash -c 'npm install && npm run dev'"

  template_nginx:
    build: ./nginx/
    image: template_nginx:1.0
    init: true
    ports:
      - "50080:80"
      - "50112:112"
    networks:
      template_net:
        ipv4_address: 172.18.0.20
    volumes:
      - ./nginx/cert:/var/cert
      - ./nginx/conf:/var/config
      - ../logs/nginx:/var/log/nginx

networks:
  template_net:
    ipam:
      driver: default
      config:
        - subnet: "172.18.0.0/24"
          gateway: 172.18.0.1
